ARG RELEASE
FROM server-dev:5000/dls-env:$RELEASE
WORKDIR /root
RUN apt-get update && apt-get install -y libxenomai-3.0.5 iit-commons-xeno iit-ecat-iface-xeno iit-io-ecat-xeno dlslab-ecat-wrappers-xeno hyq-commons-xeno hyq2max-commons-xeno hyqreal-commons-xeno





