# Docker multi-stage build to get rid of the ssh keys
# FIRST BUILD
# this is our first build stage, it will not persist in the final image
FROM ubuntu:16.04 as cloning
MAINTAINER Gennaro Raiola <gennaro.raiola@iit.it>

# Args
ARG SSH_PRIVATE_KEY  
ARG SSH_PUBLIC_KEY 

RUN apt-get -y update && apt-get install -y --no-install-recommends openssh-client

# Make SSH available
EXPOSE 22:22

# add credentials on build
RUN mkdir /root/.ssh/
RUN chmod 700 /root/.ssh/
RUN echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa
RUN echo "$SSH_PUBLIC_KEY" > /root/.ssh/id_rsa.pub
RUN cat /root/.ssh/id_rsa.pub  >> /root/.ssh/authorized_keys

RUN cat /root/.ssh/id_rsa
RUN cat /root/.ssh/id_rsa.pub

# make sure your domain is accepted
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan -t rsa gitlab.advr.iit.it 2>&1 >> /root/.ssh/known_hosts
RUN echo "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config

RUN chmod 600 /root/.ssh/*

RUN ssh -vvv git@gitlab.advr.iit.it
